[package]
name = "cqrs-data"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]

[dependencies]
cqrs = { path = "../cqrs" }
hashbrown = "0.1.3"
parking_lot = "0.6.4"
void = "1.0.2"

[dev-dependencies]
static_assertions = "*"
cqrs-todo-core = { path = "../cqrs-todo-core" }