[workspace]
members = [
    "cqrs",
    "cqrs-data",
#    "cqrs-eventstore",
    "cqrs-memory",
    "cqrs-postgres",
    "cqrs-redis",
    "cqrs-todo-core",
    "cqrs-todoql",
    "cqrs-todoql-psql",
]
