[package]
name = "cqrs"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]

[dependencies]
cqrs-core = { path = "../cqrs-core" }
hashbrown = "0.1"
parking_lot = "0.6"
void = "1.0"

[dev-dependencies]
static_assertions = "0.2"
cqrs-todo-core = { path = "../cqrs-todo-core" }