[package]
name = "cqrs"
version = "0.1.0-alpha.0"
authors = ["Marcus Griep <marcus@griep.us>"]
license = "Apache-2.0"

[dependencies]
cqrs-core = { path = "../cqrs-core" }
hashbrown = "0.1"
parking_lot = "0.7"
void = "1.0"

[dev-dependencies]
static_assertions = "0.3"
cqrs-todo-core = { path = "../cqrs-todo-core" }