[package]
name = "cqrs-postgres"
version = "0.1.0-alpha.0"
authors = ["Marcus Griep <marcus@griep.us>"]
license = "Apache-2.0"

[dependencies]
cqrs-core = { path = "../cqrs-core" }
fallible-iterator = "0.1"
log = "0.4"
postgres = "0.15"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
cqrs = { path = "../cqrs" }
cqrs-todo-core = { path = "../cqrs-todo-core" }
static_assertions = "0.3"