[package]
name = "cqrs-postgres"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]

[dependencies]
cqrs-core = { path = "../cqrs-core" }
fallible-iterator = "0.1"
log = "0.4"
postgres = "0.15"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
fnv = "*"
cqrs-todo-core = { path = "../cqrs-todo-core" }
chrono = "*"