[package]
name = "cqrs-memory"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]

[dependencies]
cqrs = { path = "../cqrs" }
cqrs-data = { path = "../cqrs-data" }
void = "1.0.2"

[dev-dependencies]
fnv = "*"
cqrs-todo-core = { path = "../cqrs-todo-core" }
chrono = "*"