[package]
name = "cqrs-memory"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]

[dependencies]
cqrs = { path = "../cqrs" }

[dev-dependencies]
fnv = "*"
cqrs-todo-core = { path = "../cqrs-todo-core" }
nickel = "*"
clap = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
