[package]
name = "cqrs-core"
version = "0.1.0-alpha.0"
authors = ["Marcus Griep <marcus@griep.us>"]
description = "Core types and traits for cqrs"
license = "Apache-2.0"
edition = "2018"

[dependencies]

[dev-dependencies]
void = "1.0"

