[package]
name = "cqrs-redis"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]

[dependencies]
cqrs-core = { path = "../cqrs-core" }
log = "0.4"
redis = "0.9"
serde = "1.0"
rmp-serde = "0.13"