[package]
name = "cqrs-todo-core"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]

[dependencies]
cqrs = { path = "../cqrs" }
smallvec = "*"
chrono = { version = "*", features = ["serde"] }
serde = "*"
serde_derive = "*"
